export const GET_ALL_DESTINS_REQUEST = "GET_ALL_DESTINS_REQUEST";
export const GET_ALL_DESTINS_SUCCESS = "GET_ALL_DESTINS_SUCCESS";
export const GET_ALL_DESTINS_FAIL = "GET_ALL_DESTINS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
