export const GET_ALL_DESTINS_REQUEST = "GET_ALL_DESTINS_REQUEST";
export const GET_ALL_DESTINS_SUCCESS = "GET_ALL_DESTINS_SUCCESS";
export const GET_ALL_DESTINS_FAIL = "GET_ALL_DESTINS_FAIL";

export const GET_DESTIN_REQUEST = "GET_DESTIN_REQUEST";
export const GET_DESTIN_SUCCESS = "GET_DESTIN_SUCCESS";
export const GET_DESTIN_FAIL = "GET_DESTIN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
