export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const PROFILE_USER_DETAILS_REQUEST = "PROFILE_USER_DETAILS_REQUEST";
export const PROFILE_USER_DETAILS_SUCCESS = "PROFILE_USER_DETAILS_SUCCESS";
export const PROFILE_USER_DETAILS_FAIL = "PROFILE_USER_DETAILS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
